# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=mymoney
quarkus.datasource.password=mymoney
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/mypersonalmoney

# Hibernate
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.validate-in-dev-mode=false

# Flyway
quarkus.flyway.migrate-at-start=true

#security
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=/login
quarkus.http.auth.form.post-location=/j_security_check
quarkus.http.auth.form.username-parameter=j_username
quarkus.http.auth.form.password-parameter=j_password
quarkus.http.auth.form.landing-page=/
quarkus.http.auth.form.error-page=/login?error=true