quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}

quarkus.flyway.migrate-at-start=true

# segurança mínima
quarkus.http.host=0.0.0.0
quarkus.http.port=8080

# (opcional) logs
quarkus.log.level=INFO